name: FreedomOpMod
main: me.StevenLawson.TotalFreedomMod.TotalFreedomMod
version: 4.8.3
description: Plugin for the FreedomOp server.
softdepend: [BukkitTelnet, LibsDisguises, WorldEdit, Essentials]
depend: [BarAPI]
authors: [Madgeek1450, DarthSalamon]

# plugin.yml is no longer used to define commands.
