name: FreedomOpMod
main: me.StevenLawson.TotalFreedomMod.TotalFreedomMod
version: 4.8
description: Plugin for the Total Freedom server.
softdepend: [BukkitTelnet, DisguiseCraft, WorldEdit, Essentials]
depend: BarAPI
authors: [Madgeek1450, DarthSalamon]

# plugin.yml is no longer used to define commands.
