name: FreedomOpMod
main: me.StevenLawson.TotalFreedomMod.TotalFreedomMod
version: 4.6
description: Plugin for the Total Freedom server.
softdepend: [BukkitTelnet, DisguiseCraft, WorldEdit, Essentials]
authors: [Madgeek1450, DarthSalamon, buildcarter8]

# plugin.yml is no longer used to define commands.
