# Name classifies the name of the folder "./plugina/{name}"
name: FreedomOPMod
# This classifies where the source files will be located
main: me.StevenLawson.TotalFreedomMod.TotalFreedomMod
# This is the version, highly suggested not to be modified.
version: 5.2
# This is the description of your plugin
description: A Minecraft plugin created for FreedomOP
# Required software for pluin to function correctly.
softdepend: [BukkitTelnet, DisguiseCraft, WorldEdit, Essentials, BarAPI, Craftbukkit/Spigiot]
# Devs/creators/coders
authors: [Madgeek1450, Prozza, buildcarter8, SupItsDillon, Robo_Lord, Dragonfire147, cowgomooo12, PieGuy7896, CrafterSmith12, hypertechHD]
